title: Ryan Lintott
logo: /assets/img/logo.png
description: This is my blog/website. I am a student at a Canadian university studying computer science. My interests include drumming, physics, math, heavy metal, and technology. Mostly I will write about my programming projects here.  
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
paginate: 5
paginate_path: "/page:num/"

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: rlintott



plugins: 
  - jekyll-paginate

